In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
one_hot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=one_hot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('one_hot_encoded_geography.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [12]:
###ANN Regression

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

c:\Users\Raghu Vamsi\Desktop\ANN Classification Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir='regression-logs/fit'+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [16]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [17]:
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),
                  epochs=100,callbacks=[early_stopping_callback,tensorboard_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 100930.3984 - mae: 100930.3984 - val_loss: 98545.5469 - val_mae: 98545.5469
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99902.8281 - mae: 99902.8281 - val_loss: 97246.9844 - val_mae: 97246.9844
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 97233.8750 - mae: 97233.8750 - val_loss: 93912.4453 - val_mae: 93912.4453
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 94718.3984 - mae: 94718.3984 - val_loss: 88244.5391 - val_mae: 88244.5391
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88078.1719 - mae: 88078.1719 - val_loss: 80734.5234 - val_mae: 80734.5234
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 80927.1953 - mae: 80927.1953 - val_loss: 72451.1484 - val_mae: 72451.1484
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 71984.6484 - mae: 71984.6484 - val_loss: 64648.1562 - val_mae: 64648.1562
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 63641.8945 - mae: 63641.8945 - val_loss: 58464.1680 - val_mae: 58464.1680
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 57039.5664 - mae: 57039.5664 - val_loss: 54377.4023 - val_mae: 54377.4023
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 54338.8516 - mae: 54338.8516 - val_loss: 52131.5391 - val_mae: 52131.5391
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51701.1797 - mae: 51701.1797 - val_loss: 51190.3789 - val_mae: 51190.3789
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50600.6367 - mae: 50600.6367 - val_loss: 50824.8867 - val_mae: 50824.8867
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50562.6211 - mae: 50562.6211 - val_loss: 50683.5781 - val_mae: 50683.5781
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50575.1602 - mae: 50575.1602 - val_loss: 50613.3906 - val_mae: 50613.3906
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50449.0938 - mae: 50449.0938 - val_loss: 50561.5586 - val_mae: 50561.5586
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49620.7930 - mae: 49620.7930 - val_loss: 50521.5195 - val_mae: 50521.5195
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50438.2969 - mae: 50438.2969 - val_loss: 50485.1797 - val_mae: 50485.1797
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49587.8320 - mae: 49587.8320 - val_loss: 50457.9219 - val_mae: 50457.9219
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49817.7891 - mae: 49817.7891 - val_loss: 50431.9336 - val_mae: 50431.9336
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50288.6562 - mae: 50288.6562 - val_loss: 50402.8555 - val_mae: 50402.8555
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50041.6641 - mae: 50041.6641 - val_loss: 50390.5234 - val_mae: 50390.5234
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50079.7852 - mae: 50079.7852 - val_loss: 50376.2695 - val_mae: 50376.2695
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49733.7734 - mae: 49733.7734 - val_loss: 50360.8047 - val_mae: 50360.8047
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49752.1094 - mae: 49752.1094 - val_loss: 50354.2773 - val_mae: 50354.2773
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49651.6523 - mae: 49651.6523 - val_loss: 50334.7656 - val_mae: 50334.7656
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49579.4570 - mae: 49579.4570 - val_loss: 50331.8359 - val_mae: 50331.8359
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49819.2500 - mae: 49819.2500 - val_loss: 50329.3242 - val_mae: 50329.3242
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49487.2695 - mae: 49487.2695 - val_loss: 50309.6719 - val_mae: 50309.6719
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49634.5195 - mae: 49634.5195 - val_loss: 50297.4844 - val_mae: 50297.4844
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50069.4297 - mae: 50069.4297 - val_loss: 50297.3008 - val_mae: 50297.3008
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49331.0625 - mae: 49331.0625 - val_loss: 50289.5039 - val_mae: 50289.5039
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50127.9023 - mae: 50127.9023 - val_loss: 50291.5039 - val_mae: 50291.5039
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49459.8555 - mae: 49459.8555 - val_loss: 50280.8281 - val_mae: 50280.8281
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49092.1836 - mae: 49092.1836 - val_loss: 50275.1953 - val_mae: 50275.1953
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49760.5078 - mae: 49760.5078 - val_loss: 50270.7344 - val_mae: 50270.7344
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50049.8750 - mae: 50049.8750 - val_loss: 50273.0859 - val_mae: 50273.0859
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50698.9141 - mae: 50698.9141 - val_loss: 50265.2578 - val_mae: 50265.2578
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49977.1289 - mae: 49977.1289 - val_loss: 50264.1406 - val_mae: 50264.1406
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49777.8906 - mae: 49777.8906 - val_loss: 50261.3828 - val_mae: 50261.3828
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49759.5625 - mae: 49759.5625 - val_loss: 50257.6914 - val_mae: 50257.6914
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49198.9531 - mae: 49198.9531 - val_loss: 50253.5742 - val_mae: 50253.5742
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49986.7461 - mae: 49986.7461 - val_loss: 50253.7188 - val_mae: 50253.7188
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49215.7656 - mae: 49215.7656 - val_loss: 50253.6406 - val_mae: 50253.6406
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49709.4688 - mae: 49709.4688 - val_loss: 50249.8906 - val_mae: 50249.8906
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50181.6328 - mae: 50181.6328 - val_loss: 50247.8984 - val_mae: 50247.8984
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49014.8555 - mae: 49014.8555 - val_loss: 50249.7422 - val_mae: 50249.7422
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49486.1562 - mae: 49486.1562 - val_loss: 50241.5586 - val_mae: 50241.5586
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49246.4727 - mae: 49246.4727 - val_loss: 50242.2852 - val_mae: 50242.2852
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50000.7539 - mae: 50000.7539 - val_loss: 50239.7812 - val_mae: 50239.7812
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49508.6445 - mae: 49508.6445 - val_loss: 50241.1602 - val_mae: 50241.1602
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49496.9844 - mae: 49496.9844 - val_loss: 50243.4922 - val_mae: 50243.4922
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50157.8906 - mae: 50157.8906 - val_loss: 50240.0039 - val_mae: 50240.0039
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49466.2070 - mae: 49466.2070 - val_loss: 50242.4297 - val_mae: 50242.4297
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49607.2383 - mae: 49607.2383 - val_loss: 50235.2891 - val_mae: 50235.2891
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49064.5195 - mae: 49064.5195 - val_loss: 50230.0859 - val_mae: 50230.0859
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49288.0742 - mae: 49288.0742 - val_loss: 50231.7539 - val_mae: 50231.7539
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49904.1289 - mae: 49904.1289 - val_loss: 50241.2266 - val_mae: 50241.2266
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49698.5938 - mae: 49698.5938 - val_loss: 50243.2266 - val_mae: 50243.2266
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49664.5312 - mae: 49664.5312 - val_loss: 50240.4492 - val_mae: 50240.4492
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49638.6172 - mae: 49638.6172 - val_loss: 50232.3008 - val_mae: 50232.3008
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49547.8555 - mae: 49547.8555 - val_loss: 50228.4961 - val_mae: 50228.4961
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49325.1914 - mae: 49325.1914 - val_loss: 50226.0000 - val_mae: 50226.0000
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49868.0977 - mae: 49868.0977 - val_loss: 50229.0508 - val_mae: 50229.0508
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49538.6992 - mae: 49538.6992 - val_loss: 50244.4297 - val_mae: 50244.4297
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49531.5938 - mae: 49531.5938 - val_loss: 50234.7461 - val_mae: 50234.7461
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49204.3867 - mae: 49204.3867 - val_loss: 50236.1172 - val_mae: 50236.1172
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50084.6641 - mae: 50084.6641 - val_loss: 50242.6602 - val_mae: 50242.6602
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49172.5000 - mae: 49172.5000 - val_loss: 50233.6328 - val_mae: 50233.6328
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49033.1250 - mae: 49033.1250 - val_loss: 50241.1758 - val_mae: 50241.1758
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49580.4688 - mae: 49580.4688 - val_loss: 50241.7812 - val_mae: 50241.7812
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 48859.9062 - mae: 48859.9062 - val_loss: 50238.7383 - val_mae: 50238.7383
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49080.5820 - mae: 49080.5820 - val_loss: 50239.4688 - val_mae: 50239.4688

In [18]:
%load_ext tensorboard

In [21]:
%tensorboard --logdir regression-logs/fit20250610-211934

In [22]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f"Test MAE:",test_mae)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51030.0820 - mae: 51030.0820
Test MAE: 50226.0

In [23]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.